title = "OpenTelemetry"
baseURL = "https://opentelemetry.io"
disableKinds = ["taxonomy", "taxonomyTerm"]
theme = ["docsy"]

enableGitInfo = true

# Language settings
contentDir = "content/en"
defaultContentLanguage = "en"
defaultContentLanguageInSubdir = false
# Useful when translating.
enableMissingTranslationPlaceholders = true

# Highlighting config
pygmentsCodeFences = true
pygmentsUseClasses = false
# Use the new Chroma Go highlighter in Hugo.
pygmentsUseClassic = false
#pygmentsOptions = "linenos=table"
# See https://help.farbox.com/pygments.html
pygmentsStyle = "tango"

# Configure how URLs look like per section.
[permalinks]
blog = "/:section/:year/:month/:day/:slug/"

[blackfriday]
hrefTargetBlank = true
plainIDAnchors = true
angledQuotes = false
latexDashes = true

# Image processing configuration.
[imaging]
resampleFilter = "CatmullRom"
quality = 75
anchor = "smart"

[languages]
[languages.en]
title = "OpenTelemetry"
description = "The OpenTelemetry Project Site"
languageName ="English"
# Weight used for sorting.
weight = 1

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
      # See a complete list of available styles at https://xyproto.github.io/splash/docs/all.html
      style = "tango"
      # Uncomment if you want your chosen highlight style used for code blocks without a specified language
      # guessSyntax = "true"


[params]
copyright = "The OpenTelemetry Authors | Documentation Distributed under CC BY 4.0 | "
<<<<<<< HEAD
=======

[params.footer]
text ="Privacy Policy"
url ="https://www.linuxfoundation.org/en/privacy/#:~:text=The%20Linux%20Foundation%27s%20core%20purpose,%2C%20a%20%E2%80%9CProject%E2%80%9D).&text=The%20Privacy%20Policy%20does%20not,employees%20or%20other%20TLF%20personnel."

>>>>>>> fbec367... added privacy policy in footer

tagline = "Effective observability requires high-quality telemetry"
sub_tagline = "**OpenTelemetry** makes robust, portable telemetry a built-in feature of cloud-native software."
sub_description = "**OpenTelemetry** provides a single set of APIs, libraries, agents, and collector services to capture distributed traces and metrics from your application. You can analyze them using Prometheus, Jaeger, and other observability tools."
font_awesome_version = "5.8.1"

# Menu title if your navbar has a versions selector to access old versions of your site.
# This menu appears only if you have at least one [params.versions] set.
version_menu = "Releases"

# Flag used in the "version-banner" partial to decide whether to display a 
# banner on every page indicating that this is an archived version of the docs.
# Set this flag to "true" if you want to display the banner.
archived_version = false

# The version number for the version of the docs represented in this doc set.
# Used in the "version-banner" partial to display a version number for the 
# current doc set.
version = "0.0"

# A link to latest version of the docs. Used in the "version-banner" partial to
# point people to the main doc site.
url_latest_version = "https://opentelemetry.io"

# Repository configuration (URLs for in-page links to opening issues and suggesting changes)
github_repo = "https://github.com/open-telemetry/opentelemetry.io"
# An optional link to a related project repo. For example, the sibling repository where your product code lives.
# github_project_repo = "https://github.com/open-telemetry"
# Change from theme default "master"
github_branch = "main"

# Google Custom Search Engine ID. Remove or comment out to disable search.
gcs_engine_id = "bde3d634eca9cd335"

# Enable Algolia DocSearch
algolia_docsearch = false

# Enable Lunr.js offline search
offlineSearch = false

# param for displaying an announcement block on homepage; see PR #377
announcement = true
# announcement_message is only displayed when announcement = true; update with your specific message
announcement_message = "<span style='padding-right:12px'>ðŸŽ‰ </span> The OpenTelemetry tracing specification is now 1.0!&nbsp;&nbsp;<a href='https://medium.com/opentelemetry/opentelemetry-specification-v1-0-0-tracing-edition-72dd08936978'>Learn more today!</a>"


# User interface configuration
[params.ui]
# Enable to show the side bar menu in its compact state.
sidebar_menu_compact = false
#  Set to true to disable breadcrumb navigation.
breadcrumb_disable = false
#  Set to true to hide the sidebar search box (the top nav search box will still be displayed if search is enabled)
sidebar_search_disable = true
#  Set to false if you don't want to display a logo (/assets/icons/logo.svg) in the top nav bar
navbar_logo = true
# Set to true to disable the About link in the site footer
footer_about_disable = true

# Adds a H2 section titled "Feedback" to the bottom of each doc. The responses are sent to Google Analytics as events.
# This feature depends on [services.googleAnalytics] and will be disabled if "services.googleAnalytics.id" is not set.
# If you want this feature, but occasionally need to remove the "Feedback" section from a single page,
# add "hide_feedback: true" to the page's front matter.
[params.ui.feedback]
enable = true
# The responses that the user sees after clicking "yes" (the page was helpful) or "no" (the page was not helpful).
yes = 'Glad to hear it! Please <a href="https://github.com/open-telemetry/opentelemetry.io/issues/new">tell us how we can improve</a>.'
no = 'Sorry to hear that. Please <a href="https://github.com/open-telemetry/opentelemetry.io/issues/new">tell us how we can improve</a>.'

# Adds a reading time to the top of each doc.
# If you want this feature, but occasionally need to remove the Reading time from a single page, 
# add "hide_readingtime: true" to the page's front matter
[params.ui.readingtime]
enable = false

[params.links]
# End user relevant links. These will show up on left side of footer and in the community page if you have one.
[[params.links.user]]
	name = "Mailing Lists"
	url = "https://github.com/open-telemetry/community#mailing-lists"
	icon = "fa fa-envelope"
        desc = "List of mailing lists that the project uses."
[[params.links.user]]
	name ="Twitter"
	url = "https://twitter.com/opentelemetry"
	icon = "fab fa-twitter"
        desc = "Follow us on Twitter to get the latest news!"
[[params.links.user]]
	name = "Stack Overflow"
	url = "https://stackoverflow.com/questions/tagged/open-telemetry"
	icon = "fab fa-stack-overflow"
        desc = "Practical questions and curated answers"
   
# Developer relevant links. These will show up on right side of footer and in the community page if you have one.
[[params.links.developer]]
	name = "GitHub"
	url = "https://github.com/open-telemetry"
	icon = "fab fa-github"
        desc = "Find us on GitHub."
[[params.links.developer]]
	name = "Slack #opentelemetry"
	url = "https://cloud-native.slack.com/archives/CJFCJHG4Q"
	icon = "fab fa-slack"
        desc = "Chat with other project developers. Sign up via https://slack.cncf.io. Other channels start with with #otel- prefix"
[[params.links.developer]]
	name = "CNCF DevStats"
	url = "https://opentelemetry.devstats.cncf.io/d/8/dashboards?orgId=1&refresh=15m"
	icon = "fas fa-chart-area"
        desc = "See our activity on CNCF DevStats"
[[params.links.developer]]
name ="Privacy Policy"
url ="https://www.linuxfoundation.org/en/privacy/#:~:text=The%20Linux%20Foundation%27s%20core%20purpose,%2C%20a%20%E2%80%9CProject%E2%80%9D).&text=The%20Privacy%20Policy%20does%20not,employees%20or%20other%20TLF%20personnel." 
icon =" fa fa-book"
desc ="CNCF works in close association with Linux Foundation. Read the privacy policy here"

[[languages.en.menu.main]]
    name = "Blog"
    weight = 50
    url = "https://medium.com/opentelemetry"


[params.logos]
hero = "opentelemetry-horizontal-color.png"
cncf = "cncf.png"

[[params.social]]
name = "GitHub"
url = "https://github.com/open-telemetry/"
color = "black"
icon = "fab fa-github"

[[params.social]]
name = "Twitter"
url = "https://twitter.com/opentelemetry"
color = "twitter"
icon = "fab fa-twitter"

[[params.social]]
name = "Slack"
url = "https://cloud-native.slack.com/archives/CJFCJHG4Q"
color = "slack"
icon = "fab fa-slack"

[[params.social]]
name = "Medium"
url = "https://medium.com/opentelemetry"
color = "light"
icon = "fab fa-medium"

[[params.social]]
name = "Mailing list"
url = "https://lists.cncf.io/g/cncf-opentelemetry-community"
color = "info"
icon = "far fa-envelope"

[[params.fonts]]
name = "Noto Sans"
sizes = [300,400,600,700]
type = "sans_serif"

