name: otel_io_excerpts
publish_to: none

environment:
  sdk: ^3.5.4

dev_dependencies:
  build_runner: ^2.4.6
  code_excerpter:
    git:
      url: https://github.com/chalin/site-shared
      path: packages/code_excerpter
  code_excerpt_updater:
    git:
      url: https://github.com/chalin/site-shared
      path: packages/code_excerpt_updater
