name: Auto-update versions

on:
  workflow_dispatch:
  schedule:
    # hourly at minute 10
    - cron: 10 * * * *

permissions: read-all

jobs:
  auto-update-versions:
    name: Auto-update versions
    runs-on: ubuntu-latest
    permissions:
      contents: write
    if: github.repository == 'open-telemetry/opentelemetry.io'
    env:
      DEPTH: --depth 999 # submodule clone depth

    steps:
      - uses: actions/checkout@v5

      - name: Use CLA approved github bot
        run: |
          git config user.name opentelemetrybot
          git config user.email 107717825+opentelemetrybot@users.noreply.github.com

      - run: ./scripts/auto-update/all-versions.sh
        env:
          # change this to secrets.GITHUB_TOKEN when testing against a fork
          GH_TOKEN: ${{ secrets.OPENTELEMETRYBOT_GITHUB_TOKEN }}
