name: Auto-update versions

on:
  workflow_dispatch:
  schedule:
    # hourly at minute 10
    - cron: 10 * * * *

jobs:
  auto-update-versions:
    name: Auto-update versions
    runs-on: ubuntu-20.04
    if: github.repository == 'open-telemetry/opentelemetry.io'
    env:
      DEPTH: --depth 100 # submodule clone depth

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use CLA approved github bot
        run: |
          git config user.name opentelemetrybot
          git config user.email 107717825+opentelemetrybot@users.noreply.github.com

      - name: Auto-update
        run: |
          .github/workflows/scripts/auto-update-version.sh opentelemetry-collector-releases vers content/en/docs/collector/_index.md
          .github/workflows/scripts/auto-update-version.sh opentelemetry-java otel content/en/docs/instrumentation/java/_index.md
          .github/workflows/scripts/auto-update-version.sh opentelemetry-java-instrumentation instrumentation content/en/docs/instrumentation/java/_index.md
          .github/workflows/scripts/auto-update-version.sh opentelemetry-specification spec scripts/content-modules/adjust-pages.pl
          .github/workflows/scripts/auto-update-version.sh opentelemetry-proto otlp scripts/content-modules/adjust-pages.pl
          .github/workflows/scripts/auto-update-version.sh semantic-conventions semconv scripts/content-modules/adjust-pages.pl
          .github/workflows/scripts/auto-update-version.sh semantic-conventions-java semconv content/en/docs/instrumentation/java/_index.md
        env:
          # change this to secrets.GITHUB_TOKEN when testing against a fork
          GH_TOKEN: ${{ secrets.OPENTELEMETRYBOT_GITHUB_TOKEN }}
