name: Auto-update versions

on:
  workflow_dispatch:
  schedule:
    # hourly at minute 10
    - cron: 10 * * * *

permissions: read-all

jobs:
  auto-update-versions:
    name: Auto-update versions
    runs-on: ubuntu-latest
    permissions:
      contents: write
    if: github.repository == 'open-telemetry/opentelemetry.io'
    env:
      DEPTH: --depth 999 # submodule clone depth

    steps:
      - uses: actions/checkout@v6

      - name: Use CLA approved github bot
        run: |
          git config user.name otelbot
          git config user.email 197425009+otelbot@users.noreply.github.com

      - uses: actions/create-github-app-token@7e473efe3cb98aa54f8d4bac15400b15fad77d94 # v2.2.0
        id: otelbot-token
        with:
          app-id: ${{ vars.OTELBOT_APP_ID }}
          private-key: ${{ secrets.OTELBOT_PRIVATE_KEY }}

      - run: ./scripts/auto-update/all-versions.sh
        env:
          # change to ${{ secrets.GITHUB_TOKEN }} and comment out the step above when testing against a fork
          GH_TOKEN: ${{ steps.otelbot-token.outputs.token }}
