name: Check collector version

on:
  workflow_dispatch:
  schedule:
    - cron: '0 * * * *'

jobs:
  build:
    name: Check collector version
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: main

      - name: Auto-update
        run: ./.github/workflows/scripts/check-collector-version.sh
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GIT_AUTHOR_NAME: opentelemetrybot
          GIT_COMMITTER_NAME: opentelemetrybot

          # Set opentelemetrybot's email, otherwise CLA checks will fail
          GIT_AUTHOR_EMAIL: 107717825+opentelemetrybot@users.noreply.github.com
          GIT_COMMITTER_EMAIL: 107717825+opentelemetrybot@users.noreply.github.com
