name: Build Semantic Conventions (daily)

on:
  schedule:
    # daily at 10:24 UTC
    - cron: "24 10 * * *"
  workflow_dispatch:

jobs:
  build-dev:
    uses: ./.github/workflows/build-dev.yml
    with:
      submodule_path_regex: semantic-conventions

  workflow-notification:
    needs:
      - build-dev
    if: always()
    uses: ./.github/workflows/reusable-workflow-notification.yml
    with:
      success: ${{ needs.build-dev.result == 'success' }}
      repo: open-telemetry/semantic-conventions
