name: Spelling

on:
  merge_group:
  pull_request:

jobs:
  spelling-check:
    name: SPELLING check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: streetsidesoftware/cspell-action@v6
        with:
          # Files should be consistent with check:spelling files
          files: |
            content/en
            data
            layouts/**/*.md
          config: .cspell.yml
          incremental_files_only: false
          suggestions: true

  dict-check:
    name: CSPELL:IGNORE check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: npm run fix:dict
      - name: Any changed files?
        run: |
          CHANGES=`git status --porcelain`
          if [[ $CHANGES ]]; then
            echo "Locally run `npm run fix:dict` and commit the changes:"
            echo "$CHANGES"
            exit 1
          else
            echo "All page-local dictionaries are well formatted."
          fi
