name: Files

on:
  merge_group:
  pull_request:

jobs:
  check-filenames:
    name: FILENAME check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: npm run check:filenames

  check-formatting:
    name: FILE FORMAT
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Create NPM cache-hash input file
        run: |
          mkdir -p tmp
          jq '{devDependencies, engines, gitHubActionCacheKey}' package.json > tmp/package-ci.json

      - uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
          cache: npm
          cache-dependency-path: tmp/package-ci.json

      - name: Install package(s)
        run: |
          PRETTIER_AT_VERS=@$(npm pkg get devDependencies.prettier | tr -d '^"')
          echo "PRETTIER_AT_VERS=$PRETTIER_AT_VERS" | tee -a $GITHUB_ENV
          npm install prettier$PRETTIER_AT_VERS --no-save
          npx prettier --version

      - run: npm run check:format
