name: Registry Validation

on:
  merge_group:
  pull_request:
    # Make sure this only runs when registry entries are touched.
    paths:
      - 'data/registry/**'

permissions:
  contents: read

jobs:
  registry-validation:
    name: REGISTRY validation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Create and use reduced-dependencies package.json
        run: |
          mkdir -p tmp
          jq '.devDependencies |= with_entries(
                  select(.key | test("gulp|markdown|through|require|yargs|js-yaml|ajv|ajv-formats|ajv-errors"))
                )
                | del(.dependencies, .optionalDependencies)' \
            package.json > tmp/package-ci.json
          cp tmp/package-ci.json package.json
      - uses: actions/setup-node@v5
        with:
          node-version-file: .nvmrc
          cache: npm
          cache-dependency-path: tmp/package-ci.json
      - run: npm install --ignore-scripts --omit=optional
      - run: npm run check:registry
