name: Spelling

on:
  merge_group:
  pull_request:

permissions:
  contents: read

jobs:
  spelling-check:
    name: SPELLING check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6.0.2
      - uses: actions/setup-node@v6
        with:
          node-version-file: .nvmrc
      - run: npm run _install:cspell --ignore-scripts
      - run: npm run check:spelling

  dict-check:
    name: CSPELL page-local word list check
    runs-on: ubuntu-latest
    env:
      FIX_CMD: fix:dict
    steps:
      - uses: actions/checkout@v6.0.2
      # Note: FIX_CMD runs fine without setup-node
      - run: npm run ${{ env.FIX_CMD }}
      - name: Any changed files?
        run: |
          CHANGES=`git status --porcelain`
          if [[ $CHANGES ]]; then
            echo "Add comment '/${{ env.FIX_CMD }}' to your PR in GitHub,"
            echo "or locally run 'npm run ${{ env.FIX_CMD }}' and commit the changes:"
            echo "$CHANGES"
            exit 1
          else
            echo "All page-local dictionaries are well formatted."
          fi
