name: Component owners
on:
  pull_request_target:

permissions:
  contents: read

jobs:
  run_self:
    runs-on: ubuntu-latest
    name: Assign component owners
    permissions:
      contents: read
      issues: write
      pull-requests: write
    if: github.repository_owner == 'open-telemetry'
    steps:
      - uses: actions/create-github-app-token@7e473efe3cb98aa54f8d4bac15400b15fad77d94 # v2.2.0
        id: otelbot-token
        with:
          app-id: ${{ vars.OTELBOT_DOCS_APP_ID }}
          private-key: ${{ secrets.OTELBOT_DOCS_PRIVATE_KEY }}
      - uses: dyladan/component-owners@v0.1.0
        with:
          config-file: .github/component-owners.yml
          # secrets.GITHUB_TOKEN can't be used here because
          # assigning org teams requires a higher privileged token
          repo-token: ${{ steps.otelbot-token.outputs.token }}
          assign-owners: false
